### ISSUE TITLE
undefined method `filter_map' in RulesCompressor#simplify

### ISSUE THREAD

**Issue by Svashtar** [CanCanCommunity/cancancan#851]
I have a bit older Rails project and and i have been using CanCanCan for years without a problem.
Today I updated the bundle and I am getting **undefined method `filter_map'** in **RulesCompressor#simplify**

Works fine on 3.5.0

### System configuration
**Rails version**: 5.2.8.1

**Ruby version**: 2.6.3

**CanCanCan version**: 3.6.0 +

**Comment by coorasse** [comment]
Yes, indeed this method is available only from ruby 2.7. 
I am not planning to keep support for ruby < 2.7, so I'd suggest you to either lock the gem or update the ruby version.
We are not testing the gem anymore for ruby < 2.7, sorry.

**Comment by mshibuya** [comment]
@coorasse Then you should raise the `required_ruby_version`, right?
https://github.com/CanCanCommunity/cancancan/blob/eab3019553dedf0ab2487e1aacd06bb16d89c703/cancancan.gemspec#L22

**Comment by coorasse** [comment]
Agree!
